# Generated by Django 5.0.2 on 2024-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charcode", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
